Add wallpaper changing

diff --git a/cucumberwm-start b/cucumberwm-start
--- a/cucumberwm-start
+++ b/cucumberwm-start
@@ -4,10 +4,19 @@
 setup-displays
 setup-sound
 
+# Set up directory for logs
 mkdir -p $HOME/.local/share/cucumberwm
 
 while true; do
-  cucumberwm &>> $HOME/.local/share/cucumberwm/cucumberwm.log
-  # If cucumberwm returns exit code 123, restart, otherwise quit.
-  [ $? -ne 123 ] && break
+    # Set a random wallpaper
+    wallpaper_num=$(shuf -i 1-305 -n 1)
+    wallpaper_path=$(printf "$HOME/Pictures/wallpapers/%.4d.jpg" $wallpaper_num)
+    feh --bg-scale $wallpaper_path
+    # Log the wallpaper chosen (so I can find it if I like it)
+    echo $wallpaper_path >> $HOME/.local/share/cucumberwm/wallpaper.log
+
+    cucumberwm &>> $HOME/.local/share/cucumberwm/cucumberwm.log
+    # If cucumberwm returns exit code 123, restart, otherwise quit.
+    [ $? -ne 123 ] && break
 done
+
